### ISSUE TITLE
achive communication between two esp32s2 board in erpc

### ISSUE THREAD

**Issue by Kingwulin** [Kerr-srl/erpc-esp#2]
Hello 
I find the example say_hello and connection is not support communication between two esp32 board.
I want to using erpc in two esp32s2 board, and make them send and recv data over uart
how can I achive it 

thanks

**Comment by Kingwulin** [comment]
Hi，@chenlijun99
would you please tell me how make it working,thanks

**Comment by chenlijun99** [comment]
Hi @Kingwulin. I have improved the hello_world example and now it also support communication between two ESP32.

**Comment by chenlijun99** [comment]
The README.md of the hello_world example should contain everything to make two ESP32 communicate with each other.

You can modify the UART pins as necessary, so that it works on your hardware. 
https://github.com/Kerr-srl/erpc-esp/blob/a13711bb3a4607e0adec6312af0b551c8ce5da44/src/examples/hello_world/main/main.c#L76-L78

**Comment by Kingwulin** [comment]
Thank you very much , it work !

**Comment by chenlijun99** [comment]
I'm glad it works!
